car_model:
# controls the rear two tires based on individual motors
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  w1_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: w1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  w4_v_controller:
    type: velocity_controllers/JointVelocityController
    joint: w4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  yaw_controller:
    type: effort_controllers/JointPositionController
    joint: yaw_joint
    pid: {p: 40000.0, i: 200.0, d: 1.0} 


